@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json

// Products
// Route that have to deal with managing products
GET {{host}}/api/products

###
GET {{host}}/api/products/5fb9d4e6a769610c6410e8a2

// Users and auth
// Route that have to deal with managing user and authentication
### Login
POST {{host}}/api/users/login
Content-Type: {{contentType}} 

{
   "email": "test@test.com",
   "password": "123456"
}

### Get Profile data
GET {{host}}/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmM4YjcwM2NkNWMyZTQzNzBiNjZlNWMiLCJpYXQiOjE2MDcwMzM4MjQsImV4cCI6MTYwOTYyNTgyNH0.ZpPAfLGbQRU-IhSXey0OEbiZOQHoHL3OOpJBbd0YbT4

###
PUT {{host}}/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmM4YjcwM2NkNWMyZTQzNzBiNjZlNWMiLCJpYXQiOjE2MDcwMzM4MjQsImV4cCI6MTYwOTYyNTgyNH0.ZpPAfLGbQRU-IhSXey0OEbiZOQHoHL3OOpJBbd0YbT4
Content-Type: {{contentType}} 

{
   "name": "test user",
   "email": "test@test.com"
}

###
POST {{host}}/api/users/register
Content-Type: {{contentType}} 

{
   "name": "Test User",
   "email": "test@test.com",
   "password": "123456"
}

###

POST {{host}}/api/orders