@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json

// Products
// Route that have to deal with managing products
GET {{host}}/api/products

###
GET {{host}}/api/products/5fb9d4e6a769610c6410e8a2

// Users and auth
// Route that have to deal with managing user and authentication
###
POST {{host}}/api/users/login
Content-Type: {{contentType}} 

{
   "email": "john@test.com",
   "password": "123456"
}

###
GET {{host}}/api/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmI5ZDRlNmE3Njk2MTBjNjQxMGU4YTAiLCJpYXQiOjE2MDY5MTU5MzMsImV4cCI6MTYwOTUwNzkzM30.GqwEWWxESCFTZM5ALsHMLihN6XzXMYrCwexGM8zMk9E

